repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: (aws|test|scripts)
        args:
          [
              "--max-line-length=88",
              "--extend-ignore=E203", # https://github.com/psf/black/issues/315
              # Q: Why extend-ignore instead of ignore? A: https://stackoverflow.com/a/68172142
          ]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.3
    hooks:
    -   id: bandit
        name: bandit
        description: 'Bandit is a tool for finding common security issues in Python code'
        entry: bandit
        language: python
        language_version: python3
        types: [ python ]
        exclude: (tests)
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: (aws|test|scripts)
        args:
          [
            "--disable=W", "--disable=R", "--disable=C", "-rn", # Only display messages
          ]