version: '3'
services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    command: [ "postgres", "-c", "log_statement=all" ] # for debugging purposes
