AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getApartmentsCount:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::616564106184:role/service-role/getApartmentsCount-role-95yp2jr0
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /apartments/count
            Method: GET
