AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  modifyApartmentsFromXLS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 900
      Role: >-
        arn:aws:iam::616564106184:role/service-role/modifyApartmentsFromXLS-role-xdug2haa
      Layers:
        - 'arn:aws:lambda:eu-west-1:616564106184:layer:xmls:2'
