"""triggers

Revision ID: 1668bb143660
Revises: 18145559121e
Create Date: 2022-04-14 22:40:19.042558

"""
from alembic import op

from kokon.utils.auditing import sync_trigger, drop_trigger


# revision identifiers, used by Alembic.
revision = "1668bb143660"
down_revision = "18145559121e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    sync_trigger(conn, "guests_version")
    sync_trigger(conn, "accommodation_units_version")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    drop_trigger(conn, "guests")
    drop_trigger(conn, "accommodation_units")
    # ### end Alembic commands ###
