"""accommodation_unit_workflow_status

Revision ID: 558b6e23830c
Revises: b6a955efb12b
Create Date: 2022-03-31 01:40:35.905369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "558b6e23830c"
down_revision = "b6a955efb12b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accommodation_units",
        "status",
        nullable=False,
        new_column_name="verification_status",
        existing_type=postgresql.ENUM(name="verificationstatus", create_type=False),
    )
    op.alter_column(
        "accommodation_units_version",
        "status",
        nullable=True,
        new_column_name="verification_status",
        existing_type=postgresql.ENUM(name="verificationstatus", create_type=False),
    )

    workflow_status_type = postgresql.ENUM(
        "AVAILABLE", "NEEDS_VERIFICATION", "WITHDRAWN", "DONE", name="workflowstatus"
    )
    workflow_status_type.create(op.get_bind())
    op.add_column(
        "accommodation_units",
        sa.Column(
            "workflow_status",
            workflow_status_type,
            server_default="NEEDS_VERIFICATION",
            nullable=True,
        ),
    )
    op.execute(
        "UPDATE accommodation_units SET workflow_status = 'NEEDS_VERIFICATION' WHERE workflow_status IS NULL;"
    )
    op.alter_column(  # pylint: disable=no-member
        "accommodation_units",
        "workflow_status",
        existing_type=workflow_status_type,
        server_default="NEEDS_VERIFICATION",
        nullable=False,
    )
    op.add_column(
        "accommodation_units_version",
        sa.Column(
            "workflow_status",
            workflow_status_type,
            server_default="NEEDS_VERIFICATION",
            autoincrement=False,
            nullable=True,
        ),
    )

    op.add_column(
        "accommodation_units",
        sa.Column("for_how_long", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "accommodation_units_version",
        sa.Column(
            "for_how_long", sa.String(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accommodation_units",
        "verification_status",
        nullable=False,
        new_column_name="status",
        existing_type=postgresql.ENUM(name="verificationstatus", create_type=False),
    )
    op.alter_column(
        "accommodation_units_version",
        "verification_status",
        nullable=True,
        new_column_name="status",
        existing_type=postgresql.ENUM(name="verificationstatus", create_type=False),
    )

    op.drop_column("accommodation_units_version", "for_how_long")
    op.drop_column("accommodation_units_version", "workflow_status")
    op.drop_column("accommodation_units", "for_how_long")
    op.drop_column("accommodation_units", "workflow_status")

    workflow_status_type = postgresql.ENUM(name="workflowstatus", create_type=False)
    workflow_status_type.drop(op.get_bind())
    # ### end Alembic commands ###
