"""extend_app_roles

Revision ID: 60eaf14d22e3
Revises: 3d11101cebad
Create Date: 2022-04-25 21:54:07.434968

"""
import os

from alembic import op


# revision identifiers, used by Alembic.
revision = "60eaf14d22e3"
down_revision = "3d11101cebad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # don't create the role for test db
    if "test" in conn.engine.url.database:
        user_name = "test_user"
    else:
        user_name = os.getenv("db_app_user", None)

    if not user_name:
        raise AssertionError("db_app_user should be specified.")

    op.execute(
        f"""
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to {user_name};
        REVOKE ALL ON accommodation_units_version FROM {user_name};
        GRANT INSERT, UPDATE(end_transaction_id), SELECT(guid, transaction_id) ON TABLE accommodation_units_version TO {user_name};
        REVOKE ALL ON guests_version FROM {user_name};
        GRANT INSERT, UPDATE(end_transaction_id), SELECT(guid, transaction_id) ON TABLE guests_version TO {user_name};
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
