"""users

Revision ID: 8e8177b6e706
Revises: 5a2877e096ed
Create Date: 2022-03-22 11:49:00.011932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8e8177b6e706"
down_revision = "5a2877e096ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "guid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("given_name", sa.String(length=100), nullable=False),
        sa.Column("family_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("google_sub", sa.String(length=255), nullable=False),
        sa.Column("google_picture", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("guid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_sub"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
