"""triggers

Revision ID: a755c3aa3ae3
Revises: b0a67ca7e616
Create Date: 2022-04-13 22:21:01.911150

"""
from alembic import op
from sqlalchemy_continuum.dialects.postgresql import sync_trigger, drop_trigger


# revision identifiers, used by Alembic.
revision = "a755c3aa3ae3"
down_revision = "b0a67ca7e616"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    sync_trigger(conn, "guests_version")
    sync_trigger(conn, "accommodation_units_version")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    drop_trigger(conn, "guests")
    drop_trigger(conn, "accommodation_units")
    # ### end Alembic commands ###
