"""guest_claimed_at

Revision ID: afd7e4278146
Revises: 43f020236495
Create Date: 2022-03-23 12:50:24.218481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "afd7e4278146"
down_revision = "43f020236495"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guests",
        sa.Column("claimed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_claimed_at()
        RETURNS TRIGGER AS $$
        BEGIN
            IF row(NEW.claimed_by_id) IS DISTINCT FROM row(OLD.claimed_by_id) THEN
                NEW.claimed_at = now();
            END IF;
            RETURN NEW;
        END;
        $$ language 'plpgsql';

        CREATE TRIGGER guest_update_claimed_at
        BEFORE INSERT OR UPDATE ON guests
        FOR EACH ROW EXECUTE PROCEDURE update_claimed_at();
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP TRIGGER guest_update_claimed_at ON guests;
        DROP FUNCTION update_claimed_at();
    """
    )

    op.drop_column("guests", "claimed_at")
    # ### end Alembic commands ###
