"""guest_claimed_at

Revision ID: afd7e4278146
Revises: 43f020236495
Create Date: 2022-03-23 12:50:24.218481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "afd7e4278146"
down_revision = "43f020236495"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guests",
        sa.Column("claimed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guests", "claimed_at")
    # ### end Alembic commands ###
