"""migration

Revision ID: cf53986008cf
Revises: b10c643435c4
Create Date: 2022-03-31 23:08:05.180384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf53986008cf"
down_revision = "b10c643435c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_accommodation_units_host_id"),
        "accommodation_units",
        ["host_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accommodation_units_version_host_id"),
        "accommodation_units_version",
        ["host_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guests_accommodation_unit_id"),
        "guests",
        ["accommodation_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guests_version_accommodation_unit_id"),
        "guests_version",
        ["accommodation_unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_host_languages_host_id"), "host_languages", ["host_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_host_languages_host_id"), table_name="host_languages")
    op.drop_index(
        op.f("ix_guests_version_accommodation_unit_id"), table_name="guests_version"
    )
    op.drop_index(op.f("ix_guests_accommodation_unit_id"), table_name="guests")
    op.drop_index(
        op.f("ix_accommodation_units_version_host_id"),
        table_name="accommodation_units_version",
    )
    op.drop_index(
        op.f("ix_accommodation_units_host_id"), table_name="accommodation_units"
    )
    # ### end Alembic commands ###
